(function(g){var window=this;var Hoa=function(a){if(!a.Ja||!a.Ja.annotations)return null;a=g.p(a.Ja.annotations);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.playerAnnotationsExpandedRenderer&&b.playerAnnotationsExpandedRenderer.featuredChannel)return b.playerAnnotationsExpandedRenderer;return null},m1=function(a){a.u||(a.u=new g.xn,g.H(a,a.u));
return a.u},n1=function(a){a.R("cardstatechange",g.DK(a)&&g.EK(a)?1:0)},Ioa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Pi&&a.dataset){if(g.gc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.cd("pollChoiceIndex"))},Joa=function(a){return Math.pow(a,3)},Koa=function(a){return 3*a*a-2*a*a*a},o1=function(a,b){(0,g.y)(b,function(c){c={csn:a,
ve:g.FA(c),eventType:4};var d={nj:void 0,zh:a};"UNDEFINED_CSN"==a?g.QA("visualElementShown",c,d):g.pr("visualElementShown",c,g.ur,d)})},p1=function(a,b){(0,g.y)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.FA(c),eventType:d?16:8};d={nj:void 0,zh:a,jC:d};"UNDEFINED_CSN"==a?g.QA("visualElementHidden",c,d):g.pr("visualElementHidden",c,g.ur,d)})},s1=function(a){a=g.Ma(a);
delete q1[a];g.Wb(q1)&&r1&&r1.stop()},t1=function(){r1||(r1=new g.J(function(){Loa()},20));
var a=r1;a.isActive()||a.start()},Loa=function(){var a=(0,g.A)();
g.Ib(q1,function(b){u1(b,a)});
g.Wb(q1)||t1()},v1=function(a,b,c,d){g.mn.call(this);
if(!g.Ha(a)||!g.Ha(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.D=null},u1=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.D);a.D=b;w1(a,a.progress);1==a.progress?(a.o=0,s1(a),a.Vc(),a.A()):1==a.o&&a.mr()},w1=function(a,b){g.Ja(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.J[c]-a.w[c])*b+a.w[c]},x1=function(a,b){g.Uj.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},y1=function(a,b,c,d,e){v1.call(this,b,c,d,e);
this.element=a},z1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
y1.call(this,a,b,c,d,e)},A1=function(a){g.E.call(this);
this.u=a||window;this.o=[]},Moa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.er(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},B1=function(a){return a.baseUrl||null},Noa=function(a,b,c){function d(U){var fa=U.hovercardButton;
if(!fa)return null;fa=fa.subscribeButtonRenderer;if(!fa)return null;var Ca=f(fa.unsubscribedButtonText),wc=f(fa.subscribedButtonText);if(fa.subscribed){var mc=f(fa.subscriberCountWithUnsubscribeText);var Xd=f(fa.subscriberCountText)}else mc=f(fa.subscriberCountText),Xd=f(fa.subscriberCountWithSubscribeText);var xc=null;return U.signinEndpoint&&(xc=g.Qb(U,"signinEndpoint","webNavigationEndpointData","url"),!xc)?null:Ca&&(wc||xc)?{subscribed:fa.subscribed,subscribeText:Ca,subscribeCount:mc,unsubscribeText:wc,
unsubscribeCount:Xd,enabled:fa.enabled,signinUrl:xc,classic:U.useClassicSubscribeButton}:null}
function e(U){if(U){var fa=[],Ca=U.videoId;Ca&&fa.push("v="+Ca);(Ca=U.playlistId)&&fa.push("list="+Ca);(U=U.startTimeSeconds)&&fa.push("t="+U);return"/watch?"+fa.join("&")}}
function f(U){if(!U)return null;var fa=U.simpleText;return fa?fa:U.runs?(0,g.ee)(U.runs,function(Ca){return Ca.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,v=null,z=null,C=!1,B=null,G=null,I=null,F=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Qb(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;q="new";(C=!!b.isSubscribe)?B=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((I=g.Qb(l,"urlEndpoint","url"))&&(m=I),n=!0,q="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&b.additionalFeesText&&(F=f(b.productPrice),M=f(b.additionalFeesText)),(a=g.Qb(l,"urlEndpoint","url"))&&(m=a),n=!0,q="new");a=g.Qb(b,"title","accessibility","accessibilityData","label");return{id:"element-"+c,type:k,title:f(b.title),metadata:f(b.metadata),callToAction:f(b.callToAction),vu:b.image,iconUrl:I,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),
aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:v,channelId:z,subscribeButton:B,subscribersText:G,isSubscribe:C,targetUrl:m,ID:n,Eb:{itct:b.trackingParams},zM:q,ej:a?a:null,MD:b.isPlaceholder,impressionUrls:(0,g.ee)(b.impressionUrls||[],B1),zD:(0,g.ee)(b.hovercardShowUrls||[],B1),clickUrls:(0,g.ee)(l.loggingUrls||[],B1),visualElement:g.EA(b.trackingParams),productPrice:F,additionalFeesText:M}},C1=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.ee)(a.impressionUrls||[],B1);a.trackingParams&&(c.visualElement=g.EA(a.trackingParams));var d=(0,g.ee)(a.elements||[],function(e,f){return Noa(b,e,f)});
c.elements=(0,g.Td)(d,function(e){return!!e});
return c},D1=function(a){g.aQ.call(this,a);
this.A=this.u=null;this.o={};this.D={};this.C=this.w=null;this.H=[];a=a.O();this.J=g.Xy(a)||g.Zy(a);this.K=!0;this.G=0;this.B=new g.Q(this);g.H(this,this.B);this.B.M(this.player,g.HD("creatorendscreen"),this.vE);this.B.M(this.player,"crx_creatorendscreen",this.wE);this.B.M(this.player,"resize",this.Aw);this.B.M(window,"focus",this.wL);this.load();var b=g.Nd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.xi(this,function(){g.Sd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},E1=function(a){return a.player.getVideoData().ac?"current":a.J?"new":"current"},F1=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},G1=function(a,b){g.gR(a.player.app,"creatorendscreen",void 0);
a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var c in a.o)a.o[c].dispose();a.o={};a.D={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){Ooa(a);c=[];var d=new g.ED(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.w=new g.W({F:"div",I:"ytp-ce-shadow"}),g.OK(a.player,a.w.element,4),a.C=new g.pM(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Poa(a,e);a.o[e.id]=f;a.D[e.id]=e;g.OK(a.player,f.element,4);var k=new g.ED(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Qoa(a,f,e)}g.KK(a.player,
c);a.Aw()}},Ooa=function(a){var b=g.ZA(),c=g.$A();
c&&b&&a.u.visualElement&&g.RA(c,b,[a.u.visualElement],void 0)},Poa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={F:"div",X:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":b.ej||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",N:H1(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",N:{href:I1(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.qn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={F:"div",X:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":b.ej||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",N:H1(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",N:{href:I1(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.qn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-playlist-count",L:[{F:"div",
I:"ytp-ce-playlist-icon"},{F:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={F:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":b.ej||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"a",X:["ytp-ce-channel-title","ytp-ce-link"],N:{href:I1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.qn(b.title||"")},W:b.title},b.subscribeButton?{F:"div",I:"ytp-ce-subscribe-container",L:[{F:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{F:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",N:H1(b)}]};c=new g.W(c);var d=g.yd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Eb.itct}else e="endscreen",f=null;e=new g.mR(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={F:"div",X:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":b.ej||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",I:"ytp-ce-expanding-overlay-body",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-website-title",N:{dir:g.qn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-website-metadata",W:b.metadata},{F:"a",X:["ytp-ce-website-goto","ytp-ce-link"],N:{href:I1(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",N:H1(b)},{F:"div",I:"ytp-ce-expanding-icon",N:J1(b.iconUrl)}]};c=new g.W(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&b.additionalFeesText&&(c={F:"div",
I:"ytp-ce-merchandise-price-container",L:[{F:"div",I:"ytp-ce-merchandise-price",W:b.productPrice},{F:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText}]}),c={F:"div",X:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":b.ej||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-merchandise-title",N:{dir:g.qn(b.title||"")},W:b.title},c,{F:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{F:"div",I:"ytp-ce-merchandise-expanded-cta-container",L:[{F:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:I1(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction},{F:"div",I:"ytp-ce-merchandise-cta-external"}]}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",
N:H1(b)},{F:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{F:"div",I:"ytp-ce-merchandise-invideo-cta",W:b.callToAction}]}]},c=new g.W(c)}b.MD&&g.K(c.element,"ytp-ce-placeholder");return c},H1=function(a){if(a.vu)var b=a.vu.thumbnails;
return J1(b?b[b.length-1].url:null)},J1=function(a){return a?{style:"background-image: url("+a+")"}:{}},Qoa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ga("mouseenter",(0,g.x)(a.tq,a,b,c));b.ga("mouseleave",(0,g.x)(a.vr,a,b,c));a.player.O().o||b.ga("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ga("click",(0,g.x)(a.by,a,c));b.ga("keypress",(0,g.x)(a.by,a,c));b.ga("focus",(0,g.x)(function(l,m){this.tq(l,m)},a,b,c));
b.ga("blur",(0,g.x)(function(l,m){this.vr(l,m)},a,b,c));
b.ga("touchstart",(0,g.x)(a.tq,a,b,c));var f=g.Bd("ytp-ce-expanding-overlay-hider",b.element);f&&b.M(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.kn(b.element,"ytp-ce-element-hover");g.kn(b.element,"ytp-ce-force-expand")});
b.ga("keydown",(0,g.x)(function(l,m){this.K=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),K1(this,m.id,!0)):(g.kn(l.element,"ytp-ce-force-expand"),g.kn(l.element,"ytp-ce-element-hover"),K1(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ga("blur",g.Na(function(){"none"!=m.style.display&&a.K&&m.focus()})),l.M(m,"focus",d),l.M(m,"blur",e))},a,b);
c(g.Bd("ytp-sb-subscribe",b.element));c(g.Bd("ytp-sb-unsubscribe",b.element));b.ga("focus",d);b.ga("blur",e)},I1=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Az(c)+b}else return"";return b},K1=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},L1=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||F1(a))c&&c();else{b=Roa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Sp(b[a],d)}},M1=function(a,b,c){L1(a,b.clickUrls,c);
(a=g.$A())&&b.ID&&g.TA(a,b.visualElement)},Roa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Soa(b[e],c));return d},Soa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},N1=function(a){return g.Ha(a)&&a.length?a[0]:a},O1=function(a){return"string"===typeof a?a:""},P1=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Uoa=function(a){var b=Toa;
if(null==a)return null;if(g.Ia(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Voa=function(a){this.externalId=a},Q1=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},R1=function(a){if(!a)return null;
var b=g.Bc(O1(a.value));b=g.zc(b);if(!b)return null;var c=P1(a.target,Woa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Q1(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},S1=function(a){return a.value?a.value:null},T1=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Toa=function(a){if(!a)return null;
var b=P1(a.type,Xoa),c=P1(a.trigger,Yoa),d=N1(a.url);d=R1(d?d:null);a=N1(a.subscribeData);var e=a?a:null;e?(a=O1(e.external_user_id),e=O1(e.subscription_token),a=a&&e?new Voa(a):null):a=null;return b?new T1(b,c,d,a):null},U1=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},V1=function(a){return(a=Zoa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Zoa=function(a,b){return g.Ua(a.o,b,void 0)},W1=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},$oa=function(a,b){this.merchant=a;
this.price=b},apa=function(a){this.o=a},bpa=function(a,b,c){b&&(c?X1(a,(0,g.ee)(b,g.Na(function(d,e){return g.Vm(e,d)},c))):X1(a,b))},X1=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Sp(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},cpa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.Xa=c;this.videoData=d;this.logger=e;this.ba=f;this.u=k},Y1=function(a,b){this.o=a;
this.w=b},epa=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(dpa(b,k))},a);
var d={F:"ul",N:{role:"radiogroup"},L:c},e={};b.Eh&&(e["aria-label"]=g.WM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{F:"div",I:"iv-card-content",L:[Z1("h2",e,b.title),{F:"form",L:[{F:"fieldset",L:[d]}]}]}];b.Eh&&(f.push("iv-card-unavailable"),d.push({F:"div",X:["iv-card-sign-in"],L:[{F:"h2",W:"Want to vote?"},{F:"a",X:["iv-card-sign-in-button","iv-button"],N:{href:S1(b.Eh)},L:[{F:"span",X:["iv-button-content"],W:"Sign in"}]}]}));f=new g.W({F:"div",
X:f,L:d});d=f.element;$1(b,d);Moa(a.o.o,d,g.Na(a.A,b),a);(0,g.y)(g.zd("iv-card-poll-choice-input",d),function(k){this.o.o.ga(k,"focus",g.Na(this.u,!0));this.o.o.ga(k,"blur",g.Na(this.u,!1))},a);
b.Eh&&(d=g.Bd("iv-card-sign-in-button",d),a.w(d,b.Eh,b.id,b.Eb,b.sc.click,5));return f},d2=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.SM?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.LD&&b.Tt?{F:"span",X:d,N:e,W:b.Tt}:"";c={F:"div",X:["iv-card",c],L:[{F:"a",I:"iv-click-target",N:{href:S1(b.url)},L:[a2(b.Hh,d?{F:"div",I:"iv-card-image-text",L:[d,b.priceText]}:""),{F:"div",I:"iv-card-content",L:[{F:"h2",I:"iv-card-primary-link",W:b.title},b2(a,b)]}]}]};c=new g.W(c);c2(a,g.zd("iv-click-target",c.element),b,b.url);return c},e2=function(a){return a.customMessage?
Z1("div","iv-card-message",a.customMessage):""},a2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{F:"div",I:"iv-card-image",N:{style:c},L:d}},b2=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(Z1("li","",d))},a);
return{F:"ul",I:"iv-card-meta-info",L:c}},dpa=function(a,b){return{F:"li",
I:W1(a,b.index),L:[{F:"label",L:[{F:"input",I:"iv-card-poll-choice-input",N:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{F:"span",I:"iv-card-poll-choice-text",L:[{F:"span",I:"iv-card-poll-choice-percent"},Z1("span",void 0,b.desc)]}]},{F:"div",I:"iv-card-poll-result",L:[{F:"div",I:"iv-card-poll-result-bar"}]}]}},Z1=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ha(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.qn(c);return{F:a,N:b,W:c}},f2=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.yl&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.yl+");");c.dir=g.qn(a.customMessage);var d=[{F:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",I:"iv-card-link-icon"}));return{F:"div",X:b,N:c,L:d}},$1=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Bd(W1(a,e.index),b);e=e.count/c;null==a.ee&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.ee==d);f.getElementsByTagName("input")[0].checked=a.ee==d;var k=Math.floor(100*e).toFixed(0),l=g.Bd("iv-card-poll-choice-percent",f);g.Zd(l,g.WM("$PERCENT%",{PERCENT:k}));f=g.Bd("iv-card-poll-result-bar",f);g.ag(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.ee);g.L(b,"iv-card-poll-expanded",
null!=a.ee&&1<a.choices.length)},c2=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Eb,c.sc.click,5)},a)},g2=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},fpa=function(a,b){return b?b:g2(a)?"current":"new"},h2=function(a,b){g.E.call(this);
this.o=a;this.context=b;this.Fs=!1},gpa=function(a,b,c,d,e){var f=S1(b);
if(f){var k=fpa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.ba.pauseVideo();var m=this.context.videoData.ac||!1,n=g.fp(f||"");m&&n&&(n.v||n.list)?g.MT(this.context.ba.app,n.v,c,n.list,!1,void 0):g.bN(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);X1(a.context.logger,d,l,e);g2(f)||(a=g.$A(),d=c.itct,a&&d&&g.TA(a,g.EA(d)))}},i2=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},j2=function(a,b,c){return{Iv:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Qz:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Sn:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},m2=function(a,b,c){h2.call(this,b,c);
var d=this;this.w=a;this.Z=this.ya=this.C=this.xa=!1;this.aa=null;this.da=new g.J(g.Ea,c.Xa.dd?4E3:3E3);g.H(this,this.da);this.la=new g.J(g.Ea);g.H(this,this.la);this.H=new Y1(c,(0,g.x)(this.Qi,this),(0,g.x)(this.Em,this));this.T=new g.W({F:"div",I:"iv-drawer",N:{id:"iv-drawer"},L:[{F:"div",I:"iv-drawer-header",N:{"aria-role":"heading"},L:[{F:"span",I:"iv-drawer-header-text"},{F:"button",X:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",I:"iv-drawer-content"}]});
g.H(this,this.T);this.D=this.T.element;this.oa=new g.pM(this.T,330);g.H(this,this.oa);this.wa=g.Bd("iv-drawer-header-text",this.D);this.B=g.Bd("iv-drawer-content",this.D);this.A=[];this.na=this.P=this.G=this.fa=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.ya&&k2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ya=d.C)&&l2(d)});
this.U=this.J=this.ca=null;this.K=0},hpa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){k2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){l2(a)});
var c=b.data.headerText;g.Zd(a.wa,c);a.P&&a.P.setAttribute("title",c);a.ca=g.EA(b.data.trackingParams);a.U=g.EA(b.data.closeTrackingParams);a.J=g.EA(b.data.iconTrackingParams)},ipa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"simple",teaserText:g.PB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Eb:n2(a,c,b),sponsored:!1,sc:j2(d,e,d.command),Dd:d.trackingParams?g.EA(d.trackingParams):null,zd:e.trackingParams?
g.EA(e.trackingParams):null,Pc:f&&f.trackingParams?g.EA(f.trackingParams):null,imageUrl:d.image.thumbnails[0].url,displayDomain:d.displayDomain?g.PB(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,yl:null,title:d.title?g.PB(d.title):"",customMessage:d.callToAction?g.PB(d.callToAction):"",url:d.command.urlEndpoint.url?R1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:d.command.urlEndpoint.url}):null};o2(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"collaborator",teaserText:g.PB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Eb:n2(a,c,b),sponsored:!1,sc:j2(d,e,d.endpoint),Dd:d.trackingParams?g.EA(d.trackingParams):null,zd:e.trackingParams?g.EA(e.trackingParams):null,Pc:f&&f.trackingParams?g.EA(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.PB(d.customText):null,Sy:d.channelAvatar.thumbnails[0].url,title:d.channelName?g.PB(d.channelName):"",metaInfo:[d.subscriberCountText?g.PB(d.subscriberCountText):""],url:R1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};o2(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"playlist",teaserText:g.PB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Eb:n2(a,c,b),sponsored:!1,sc:j2(d,e,d.action),Dd:d.trackingParams?g.EA(d.trackingParams):null,zd:e.trackingParams?g.EA(e.trackingParams):null,Pc:f&&f.trackingParams?g.EA(f.trackingParams):
null,Hh:d.playlistThumbnail.thumbnails[0].url,customMessage:d.customMessage?g.PB(d.customMessage):null,playlistVideoCount:g.PB(d.playlistVideoCount),title:d.playlistTitle?g.PB(d.playlistTitle):"",metaInfo:[d.channelName?g.PB(d.channelName):"",d.videoCountText?g.PB(d.videoCountText):""],url:R1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:i2(d.action)})};o2(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"video",teaserText:g.PB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Eb:n2(a,c,b),sponsored:!1,sc:j2(d,e,d.action),Dd:d.trackingParams?g.EA(d.trackingParams):null,zd:e.trackingParams?g.EA(e.trackingParams):null,Pc:f&&f.trackingParams?g.EA(f.trackingParams):null,Hh:d.videoThumbnail.thumbnails[0].url,
videoDuration:d.lengthString?g.PB(d.lengthString):null,customMessage:d.customMessage?g.PB(d.customMessage):null,title:d.videoTitle?g.PB(d.videoTitle):"",metaInfo:[d.channelName?g.PB(d.channelName):"",d.viewCountText?g.PB(d.viewCountText):""],isLiveNow:!!d.badge,url:R1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:i2(d.action)})};o2(a,c)}a.K++},n2=function(a,b,c){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:c.trackingParams}},q2=function(a,b){var c=jpa(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.Sd(c.Oo),g.ab(a.A,c),a.Al(),p2(a))},k2=function(a,b,c){if(!a.C){a.oa.show();
a.fa=new g.J(function(){g.K(a.context.ba.getRootNode(),"ytp-iv-drawer-open")},0);
a.fa.start();a.aa=g.Wq(a.B,"mousewheel",(0,g.x)(a.SE,a));a.C=!0;var d=g.$A();d&&a.ca&&a.U&&o1(d,[a.ca,a.U]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.lw||(f.lw=!0,bpa(a.context.logger,f.card.sc.Iv,e));d&&o1(d,[f.card.Dd])});
n1(a.w);c&&(a.G=new g.J(function(){a.ea=a.P;a.na.focus()},330),a.G.start())}},l2=function(a){a.C&&(a.oa.hide(),g.Xq(a.aa),a.aa=null,g.kn(a.context.ba.getRootNode(),"ytp-iv-drawer-open"),a.C=!1,n1(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.ea&&(a.ea.focus(),a.ea=null)},330),a.G.start())},kpa=function(a){var b=g.Bd("iv-drawer-close-button",a.D);
a.context.o.ga(b,"click",a.SB,a);a.context.o.ga(a.B,"touchend",function(){a.da.start()});
a.context.o.ga(a.B,"scroll",a.gC,a);a.context.u.subscribe("onHideControls",function(){a.Z=!0});
a.context.u.subscribe("onShowControls",function(){a.Z=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Z=g.hn(a.w.getRootNode(),"ytp-autohide")});
a.V.push(g.Eo("iv-button-shown",a.XD,a));a.V.push(g.Eo("iv-button-hidden",a.VD,a));a.V.push(g.Eo("iv-teaser-shown",a.aE,a));a.V.push(g.Eo("iv-teaser-hidden",a.ZD,a));a.V.push(g.Eo("iv-teaser-clicked",a.YD,a))},o2=function(a,b){a.xa||(g.jn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.OK(a.w,a.D,5),kpa(a),a.P=g.Bd("ytp-cards-button",a.w.getRootNode()),a.na=g.Bd("iv-drawer-close-button",a.D),a.xa=!0);q2(a,b.id);var c=lpa(a,b);if(c){var d={card:b,Oo:c.element,lw:!1},e=mpa(a,d);g.gb(a.A,e,0,d);c.o(a.B,e);a.Al();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Na(a.iM,d)):(c=1E3*a.context.ba.getCurrentTime(),5E3>c&&c>b.startMs&&a.zz(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Na(a.zz,d)),p2(a))}},lpa=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{F:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=f2(b);d={F:"div",X:["iv-card"],L:[{F:"a",I:"iv-click-target",N:{href:S1(b.url)},L:[a2(b.imageUrl,d),{F:"div",I:"iv-card-content",L:[Z1("h2",void 0,b.title),e]}]}]};d=new g.W(d);c2(c,g.zd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={F:"div",X:["iv-card","iv-card-channel"],L:[{F:"a",X:["iv-click-target"],N:{href:S1(b.url),"data-ytid":b.channelId},L:[a2(b.Sy),{F:"div",I:"iv-card-content",
L:[e2(b),{F:"h2",I:"iv-card-primary-link",W:b.title},b2(c,b)]}]}]},d=new g.W(d),c2(c,g.zd("iv-click-target",d.element),b,b.url),d;case "episode":return d2(a.H,b,"iv-card-episode");case "movie":return d2(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={F:"div",X:["iv-card","iv-card-playlist"],L:[{F:"a",I:"iv-click-target",N:{href:S1(b.url)},L:[a2(b.Hh,{F:"div",I:"iv-card-image-overlay",L:[{F:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{F:"div",I:"iv-card-content",L:[e2(b),
Z1("h2","iv-card-primary-link",b.title),b2(c,b)]}]}]},d=new g.W(d),c2(c,g.zd("iv-click-target",d.element),b,b.url),d;case "poll":return epa(a.H,b);case "productListing":c=a.H;var f=!g.Ya(b.offers);d=["iv-card"];e="";var k=f2(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({F:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({F:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={F:"div",L:k});d={F:"div",X:d,N:{tabindex:"0"},L:[{F:"a",X:["iv-card-image",
"iv-click-target"],N:{style:"background-image: url("+b.imageUrl+");",href:S1(b.url),"aria-hidden":"true",tabindex:"-1"}},{F:"div",I:"iv-card-content",L:[b.sponsored?{F:"div",I:"iv-card-sponsored",L:["Sponsored",{F:"div",I:"iv-ad-info-container",L:[{F:"div",I:"iv-ad-info",W:"{{adInfo}}"},{F:"div",I:"iv-ad-info-icon-container",L:[{F:"div",I:"iv-ad-info-icon"},{F:"div",I:"iv-ad-info-callout"}]}]}]}:"",{F:"a",I:"iv-click-target",N:{href:S1(b.url)},L:[Z1("h2",e,b.title),k]}]}]};d=new g.W(d);e=g.Nd("span");
g.Zd(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.jb(e,"adInfo");c2(c,g.zd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{F:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={F:"div",X:["iv-card","iv-card-video"],L:[{F:"a",I:"iv-click-target",N:{href:S1(b.url)},L:[a2(b.Hh,b.videoDuration?{F:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{F:"div",I:"iv-card-content",
L:[e2(b),Z1("h2","iv-card-primary-link",b.title),b2(c,b),d]}]}]},d=new g.W(d),c2(c,g.zd("iv-click-target",d.element),b,b.url),d}return null},mpa=function(a,b){if(0==a.A.length)return 0;
var c=g.Va(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},npa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.$g)(a.A,function(b){return"productListing"==b.card.type})},p2=function(a){g.L(a.w.getRootNode(),"ytp-cards-shopping-active",npa(a))},r2=function(a,b){if(a.T.Ha()){var c=new v1([0,
a.B.scrollTop],[0,b.Oo.offsetTop],600,Koa);a.context.w.ga(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ga(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.Gu(a.T,!0),a.B.scrollTop=b.Oo.offsetTop,g.Gu(a.T,!1)},s2=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},jpa=function(a,b){return g.Ua(a.A,function(c){return c.card.id==b})},t2=function(a,b,c){h2.call(this,a,b);
this.annotation=c;this.isActive=!1},opa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},u2=function(a,b,c){t2.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.D=this.C=null},v2=function(a,b,c){t2.call(this,a,b,c);
this.J=this.C=this.K=!1;this.G=5E3;this.B=null;this.H=g.Md("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.D=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.ug(this.A,!1);g.ug(this.w,!0)},700,this);
g.H(this,this.D)},ppa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=V1(a.annotation),f=b.image_url;if(f){var k=g.Md("DIV",["iv-promo-img","iv-click-target"]);f=g.Md("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Md("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Md("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Qi(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Md("A","iv-promo-txt"),g.Sc(f,S1(e)),a.u=f):a.u=g.Md("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Md("P",null,g.Md("STRONG",null,b.text_line_1));var m=g.Md("P",null,g.Md("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.Xa.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Md("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Md("BUTTON",["iv-button","iv-promo-button"],g.Md("SPAN","iv-button-content",f));var q=g.Md("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Qi(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.Qi(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Md("P",null,g.Md("SPAN",null,b.text_line_1)),
m=g.Md("P",null,g.Md("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Md("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.Qi(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Md("DIV","iv-promo-actions");a.w=g.Md("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ga(a.w,"click",g.Na(a.Ep,5E3),a);c.appendChild(a.w);g.ug(a.w,!1);
a.context.o.ga(a.o,"mouseover",a.dD,a);a.context.o.ga(a.o,"mouseout",a.cD,a);a.context.o.ga(a.o,"touchend",g.Na(a.Ep,5E3),a);a.A=g.Md("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ga(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.WC:a.VC,a);c.appendChild(a.A);g.jn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},w2=function(a){a.C||a.J||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.D.start())},x2=function(a){a.D.stop();
a.C&&(g.ln(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.ug(a.w,!1),g.ug(a.A,!0))},z2=function(a,b){a.B||(a.B=g.dl(function(){y2(this);
w2(this)},b,a))},y2=function(a){a.B&&(g.u.clearTimeout(a.B),a.B=null)},A2=function(a){g.aQ.call(this,a);
this.J=!1;this.H=0;this.D={};this.T=new apa(a);this.B=new g.Q(this);g.H(this,this.B);this.C=this.w=null;this.B.M(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.M(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.M(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.M(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.M(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.TJ,this);this.subscribe("resize",this.un,this);this.player.O().G.subscribe("vast_info_card_add",this.Fy,this);this.P=new g.Q(this);g.H(this,this.P);this.U=g.Md("DIV","video-custom-annotations");this.u=new g.W({F:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.OK(this.player,this.u.element,4);this.u.hide();this.A=new g.W({F:"div",X:["ytp-iv-video-content"]});g.H(this,this.A);g.Pd(this.A.element,g.Md("DIV","video-annotations",
this.U));this.G=this.o=null;this.K=[];qpa(this)&&this.load();var b=g.Nd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.xi(this,function(){g.Sd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},B2=function(){var a=g.Md("DIV",["annotation",
"annotation-type-custom"]);g.ug(a,!1);return a},C2=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},qpa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.uA||null!==b.G.get(a.videoId)},D2=function(a,b,c){a.J=!0;
a.C=g.zp(b,c)},E2=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ka(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(E2(a,e))}return c},F2=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},rpa=function(a){var b=a.player.getVideoData();
if(b.Cd){var c=a.player.O().G.get(b.videoId);if(c){var d={format:"XML",od:{},method:"POST",withCredentials:!0};d.Vc=(0,g.x)(function(e,f,k){F2(this,e,f)||(e=g.tp(k)&&k.responseXML?k.responseXML:null)&&G2(this,e)},a,a.H,b.videoId);
g.Wo()&&(d.Vc=H2(a,d.Vc));d.tb={ic_only:"1"};I2(d,c);a.J=!0;g.zp(b.Cd,d)}}},I2=function(a,b){a.method="POST";
a.tb=a.tb||{};b.El&&(a.tb.ic_coll=b.El);b.Fl&&(a.tb.ic_xml=b.Fl);b.us&&(a.tb.ic_track=b.us)},K2=function(a){var b=new g.W({F:"div"});
g.ug(b.element,!1);var c=new m2(a.player,b.element,J2(a));g.H(c,b);b.o(a.u.element);c.Ek();return c},J2=function(a){if(!a.G){var b=new A1(a);
g.H(a,b);var c=new g.j_(a);g.H(a,c);a.G=new cpa(b,c,a.player.O(),a.player.getVideoData(),a.T,a.player,a.Tb)}return a.G},G2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.$A();if(e){var f=g.ZA();f&&g.RA(e,f,[g.EA(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=E2(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=P1(k.type,spa),t=P1(k.style,tpa),v=O1(k.data),z=0!=v.length?JSON.parse(v):{},C=Uoa(k.action);f=n&&q?new U1(n,q,t,C,z):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var B=B2(),G=null;switch(m.type){case "branding":if(k.player.O().fc)break;k.u.element.appendChild(B);G=new u2(B,J2(k),m);break;case "promotion":g.OK(k.player,B,4),G=new v2(B,J2(k),m)}G&&G.Ek();if(k=G)g.H(a,k),a.D[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=K2(a),g.H(a,a.o));if("card"==f.type){if(c=a.o,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Iv:k.impression,click:k.click,close:k.close,Qz:k.teaser_impression,Sn:k.teaser_click},m=f.data.tracking_params||
{},B=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Eb:f.data.session_data||{},sponsored:f.data.sponsored||!1,sc:k,Dd:m.card?g.EA(m.card):null,zd:m.teaser?g.EA(m.teaser):null,Pc:m.icon?g.EA(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,Sy:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:R1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o2(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Eb:f.data.session_data||{},sponsored:f.data.sponsored||!1,sc:k,Dd:m.card?g.EA(m.card):null,zd:m.teaser?g.EA(m.teaser):null,Pc:m.icon?g.EA(m.icon):
null,Hh:f.data.image_url,Tt:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,LD:!!f.data.is_paygated,SM:!!f.data.user_has_entitlement,url:R1({target:f.data.target||"new",value:f.data.url})};o2(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Eb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,sc:k,Dd:m.card?g.EA(m.card):null,zd:m.teaser?g.EA(m.teaser):null,Pc:m.icon?g.EA(m.icon):null,Hh:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:R1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o2(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Eb:f.data.session_data||{},sponsored:f.data.sponsored||!1,sc:k,Dd:m.card?g.EA(m.card):null,zd:m.teaser?g.EA(m.teaser):null,Pc:m.icon?g.EA(m.icon):null,title:f.data.title,choices:f.data.choices,ee:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Eh:f.data.signin_url?R1({target:"current",value:f.data.signin_url}):null,dN:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};o2(c,f);break;case "productListing":f.data.signin_url&&(B=R1({target:"current",
value:f.data.signin_url}));G=[];for(var I=f.data.offers||[],F=0;F<I.length;F++)G.push(new $oa(g.Zc(I[F].merchant),g.Zc(I[F].price)));f={bR:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Eb:f.data.session_data||{},sponsored:f.data.sponsored||!1,sc:k,Dd:m.card?g.EA(m.card):null,zd:m.teaser?g.EA(m.teaser):null,Pc:m.icon?g.EA(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,yl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:R1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Eh:B,mR:f.data.signin_title?f.data.signin_title:null,lR:f.data.signin_message?f.data.signin_message:null,offers:G};o2(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Eb:f.data.session_data||{},sponsored:f.data.sponsored||!1,sc:k,Dd:m.card?g.EA(m.card):null,zd:m.teaser?g.EA(m.teaser):null,Pc:m.icon?g.EA(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,yl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:R1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o2(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Eb:f.data.session_data||{},sponsored:f.data.sponsored||!1,sc:k,Dd:m.card?g.EA(m.card):null,zd:m.teaser?g.EA(m.teaser):
null,Pc:m.icon?g.EA(m.icon):null,Hh:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:R1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},o2(c,f)}}else hpa(a.o,f);c=!0}}}c&&(n1(a.player),a.un())},upa=function(a,b){var c=!1;
a.o||(a.o=K2(a),g.H(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())ipa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.PB(b.headerText):"",g.Zd(c.wa,d),c.P&&c.P.setAttribute("title",d),c.ca=b.trackingParams?g.EA(b.trackingParams):null,c.U=b.closeButton.infoCardIconRenderer.trackingParams?g.EA(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.EA(b.icon.infoCardIconRenderer.trackingParams):null,n1(a.player),a.un())},
vpa=function(a,b,c,d,e){if(!a.player.O().fc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new T1("openUrl","click",new Q1("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;b.subscribed?(e=g.PB(b.subscriberCountWithUnsubscribeText),k=g.PB(b.subscriberCountText)):(e=g.PB(b.subscriberCountText),k=g.PB(b.subscriberCountWithSubscribeText));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.PB(b.unsubscribedButtonText),
subscribeCount:e,unsubscribeText:g.PB(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new U1(c,"branding","branding",f,d);d=B2();a.u.element.appendChild(d);f=new u2(d,J2(a),f);f.Ek();g.H(f,f);a.D[c]=f}},H2=function(a,b){return(0,g.x)(function(){if(!this.ha()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Na.apply(window,c);this.K.push(g.Uo(b))}},a)},q1={},r1=null;g.Pa(v1,g.mn);g.h=v1.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;s1(this);this.startTime=a=(0,g.A)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.B();this.Ud("play");-1==this.o&&this.Ud("resume");this.o=1;var b=g.Ma(this);b in q1||(q1[b]=this);t1();u1(this,a);return!0};
g.h.stop=function(a){s1(this);this.o=0;a&&(this.progress=1);w1(this,this.progress);this.Ud("stop");this.A()};
g.h.pause=function(){1==this.o&&(s1(this),this.o=-1,this.Ud("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.Ud("destroy");v1.xb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.mr=function(){this.Ud("animate")};
g.h.Ud=function(a){this.dispatchEvent(new x1(a,this))};
g.Pa(x1,g.Uj);g.Pa(y1,v1);y1.prototype.C=g.Ea;y1.prototype.mr=function(){this.C();y1.xb.mr.call(this)};
y1.prototype.A=function(){this.C();y1.xb.A.call(this)};
y1.prototype.B=function(){this.C();y1.xb.B.call(this)};
g.Pa(z1,y1);z1.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(A1,g.E);A1.prototype.ga=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Wq(a,b,c);this.o.push(a);return a};
A1.prototype.fq=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.fr(a,b,c);this.o.push(a);return a};
A1.prototype.Ta=function(a){g.Xq(a);g.ab(this.o,a)};
A1.prototype.Y=function(){g.Xq(this.o);this.o.length=0;g.E.prototype.Y.call(this)};g.r(D1,g.aQ);g.h=D1.prototype;g.h.load=function(){g.aQ.prototype.load.call(this);if(!F1(this)){var a=g.FC(this.player.getVideoData());if(a)a=C1(a,E1(this)),G1(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",Vc:(0,g.x)(this.FI,this,a),od:{v:a},withCredentials:!0};this.J&&(a.od.ptype="embedded");var c=this.player.getVideoData().Ql;c&&(a.tb={ad_tracking:c});if(b=g.EC(b))if(b=g.Bc(b),b=g.zc(b))this.A=g.zp(b,a)}}};
g.h.unload=function(){G1(this,null);this.A&&(this.A.abort(),this.A=null);g.aQ.prototype.unload.call(this)};
g.h.wc=function(a,b){if(!F1(this))return null;if("loadCustomEndscreenRenderer"==a){var c=C1(b,"new");G1(this,c);return!0}return null};
g.h.getOptions=function(){return F1(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.FI=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=C1(c,E1(this)))}G1(this,c)};
g.h.Aw=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<L2.length;f++){var k=Math.abs(b.width-L2[f]);if(-1==e||d>=k)e=f,d=k}d=M2[e];this.w&&g.ag(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.sg(e.element,Math.round(k.width*a.width),f);g.ig(e.element,m,n);g.ln(e.element,wpa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ln(e.element,M2);g.K(e.element,d);(e=g.yd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ag(e,"height",f+"px")}}}}};
g.h.vE=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())L1(this,this.u.impressionUrls),(a=g.$A())&&this.u.visualElement&&g.SA(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.D[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");L1(this,c.impressionUrls);(b=g.$A())&&g.SA(b,c.visualElement);this.player.O().wb&&this.player.ka("endscreenelementshown",a)}};
g.h.wE=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.kn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.kn(b,"ytp-ce-shown");this.player.O().wb&&this.player.ka("endscreenelementhidden",a)}};
g.h.wL=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.ln(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.by=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.hn(c,"ytp-ce-element");){g.hn(c,"subscribe-label")&&M1(this,a);if(g.hn(c,"ytp-ce-channel-subscribe"))return;c=g.Vd(c)}if(!c||g.hn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.vr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.zM?(M1(this,a),this.yz(),this.player.pauseVideo(),c=g.Bc(I1(this,a.targetUrl)),c=g.zc(c),g.bN(c,void 0,a.Eb)):(c=this.player.getVideoData().ac,
c=(0,g.x)(this.qM,this,c,I1(this,a.targetUrl),a.Eb),c=(0,g.x)(this.yz,this,c),M1(this,a,c))}}};
g.h.qM=function(a,b,c){var d=g.fp(b);a&&d&&(d.v||d.list)?g.MT(this.player.app,d.v,c,d.list,!1,void 0):g.aN(b,c)};
g.h.tq=function(a,b){g.hn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.J(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),L1(this,b.zD),K1(this,b.id,!0))};
g.h.vr=function(a,b){g.kn(a.element,"ytp-ce-element-hover");g.kn(a.element,"ytp-ce-force-expand");K1(this,b.id,!1)};
g.h.yz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var L2=[346,426,470,506,570,640,853,1280,1920],M2="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),wpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Woa={kO:"current",DP:"new"};var Xoa={CLOSE:"close",GP:"openUrl",oB:"subscribe"},Yoa={dO:"click",CLOSE:"close",VO:"hidden",dQ:"rollOut",eQ:"rollOver",hQ:"shown"};var tpa={FN:"anchored",KA:"branding",CHANNEL:"channel",jO:"cta",XO:"highlightText",mP:"label",PLAYLIST:"playlist",QP:"popup",lQ:"speech",oB:"subscribe",vQ:"title",VIDEO:"video",IQ:"website"},spa={KA:"branding",UN:"card",qO:"drawer",WO:"highlight",tP:"marker",VP:"promotion",TEXT:"text",KQ:"widget"};Y1.prototype.u=function(a,b){var c=g.de(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
Y1.prototype.A=function(a,b){var c=g.de(b.target,null,"iv-card-poll",void 0);if(c)if(a.Eh)g.Bd("iv-card-sign-in-button",c).click();else{var d=parseInt(Ioa(b.target),10);if(null==a.ee)a.choices[d].count++,a.ee=d;else if(a.ee!=d){var e=a.choices[a.ee];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.ee=d}else e=a.choices[a.ee],e.count=Math.max(e.count-1,0),a.ee=null;$1(a,c);g.Dp(this.o.videoData.Cd,{od:{action_poll_vote:1},tb:{poll_id:a.id,index:d,session_token:a.dN}});X1(this.o.logger,a.sc.click,
void 0,5);(c=g.$A())&&a.Dd&&g.TA(c,a.Dd)}};g.r(h2,g.E);g.h=h2.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.ED(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&m1(a).subscribe("onEnter",d,this);e&&m1(a).subscribe("onExit",e,this);g.KK(this.context.ba,[a])};
g.h.Ek=function(){this.context.u.subscribe("resize",this.Al,this)};
g.h.Qi=function(a,b,c,d,e,f){this.context.o.ga(a,"click",g.Na(this.Em,b,c,d,e||[],f||0),this);this.context.o.ga(a,"touchstart",g.Na(function(){this.Fs=!1}),this);
this.context.o.ga(a,"touchmove",g.Na(function(){this.Fs=!0}),this)};
g.h.Em=function(a,b,c,d,e,f){if(this.Fs)return!1;f&&(f.stopPropagation(),f.preventDefault());gpa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Sd(this.o)};
g.h.Al=function(){};g.r(m2,h2);g.h=m2.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.w.getRootNode())?(a=g.tg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Al=function(){var a=this.isAvailable();g.ug(this.o,a);g.L(this.context.ba.getRootNode(),"ytp-iv-drawer-enabled",a);n1(this.w)};
g.h.destroy=function(){var a=g.CK(g.qK(this.w));a&&a.rq(!1,void 0);this.w.getRootNode().removeChild(this.D);g.Fo(this.V);g.Xq(this.aa);this.fa&&this.fa.dispose();this.G&&this.G.dispose();h2.prototype.destroy.call(this)};
g.h.SE=function(a){this.da.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.zz=function(a){if(!g.hn(this.w.getRootNode(),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.$A(),c=this.u?this.u.card.Pc:this.J;b&&c&&p1(b,[c]);this.u=a;p2(this)}if(b="none"!=this.o.style.display)2==this.context.ba.getPresentingPlayerType()?b=1==this.context.ba.getAdState():(b=this.context.ba.getPlayerState(),c=0==b&&0===this.context.ba.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.CK(g.qK(this.w)))&&c.rq(!0,
b));this.la.isActive()||((!this.C||!this.da.isActive()&&this.Z)&&r2(this,a),this.la.start(910+a.card.teaserDurationMs))}};
g.h.iM=function(a){this.C||(this.u=a,p2(this),r2(this,a),k2(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.SB=function(){if(this.C){X1(this.context.logger,s2(this).sc.close);var a=g.$A();a&&this.U&&g.TA(a,this.U);l2(this)}};
g.h.gC=function(){g.L(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.XD=function(){var a=g.$A(),b=s2(this);b=b?b.Pc:this.J;a&&b&&o1(a,[b])};
g.h.VD=function(){var a=g.$A(),b=s2(this);b=b?b.Pc:this.J;a&&b&&p1(a,[b])};
g.h.aE=function(){var a=s2(this);X1(this.context.logger,a.sc.Qz);var b=g.$A();b&&a&&o1(b,[a.zd,a.Pc])};
g.h.ZD=function(){var a=g.$A(),b=s2(this);a&&b&&p1(a,[b.zd])};
g.h.YD=function(a){var b=s2(this),c=g.$A();this.u?a?(a=this.context.logger,X1(a,b.sc.Sn),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.zd&&g.TA(c,b.zd)):(a=this.context.logger,X1(a,b.sc.Sn),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Pc&&g.TA(c,b.Pc)):(a=this.context.logger,X1(a,b.sc.Sn),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.TA(c,this.J))};g.r(t2,h2);t2.prototype.Ek=function(){h2.prototype.Ek.call(this);opa(this)};
t2.prototype.show=function(){h2.prototype.show.call(this);var a=g.$A(),b=this.annotation.data;a&&b&&(b=b.session_data)&&o1(a,[g.EA(b.itct)])};
t2.prototype.hide=function(){h2.prototype.hide.call(this);var a=g.$A(),b=this.annotation.data;a&&b&&(b=b.session_data)&&p1(a,[g.EA(b.itct)])};g.r(u2,t2);g.h=u2.prototype;g.h.rM=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.tg(a);this.u||(g.rg(a,e.width),g.rg(b,e.width));g.ag(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ag(c,"right","1px");this.B=!0;g.ug(a,!0);this.C=new g.J(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.xD=function(a,b){g.kn(this.o,"iv-branding-active");this.D=new g.J((0,g.x)(function(){g.ug(a,!1);this.u||g.rg(b,0)},this),250);
this.D.start();this.B=!1};
g.h.show=function(){if(!this.isActive){t2.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Md("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.ug(this.w,!1);var b=g.Md("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=V1(this.annotation))&&this.Qi(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Md("DIV","iv-branding-context-name");
g.Zd(c,a.channel_name);var d=g.Md("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.mR(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ba),this.u.o(d);b=g.Md("DIV","iv-branding-context-subscribe-caret");c=g.Md("DIV","branding-context-container-inner",b,c,d);g.ug(c,!1);d=g.Md("DIV","branding-context-container-outer",c);g.ag(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Na(this.xD,c,d),500,this);g.H(this,this.A);this.context.o.ga(this.o,"mouseover",(0,g.x)(this.rM,this,c,d,b,a.image_height));this.context.o.ga(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.ug(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.mg(a);c=g.tg(a);b=(new g.Yf(b.x,b.y,c.width,c.height)).width;g.ig(a,b);e=new z1(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,Joa);g.H(this,e);this.context.w.ga(e,
"begin",g.Na(g.ug,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(t2.prototype.hide.call(this),g.ug(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);t2.prototype.destroy.call(this)};g.r(v2,t2);g.h=v2.prototype;g.h.show=function(){this.isActive||(t2.prototype.show.call(this),this.K||(ppa(this),this.K=!0),g.ug(this.o,!0),g.dl(function(){g.kn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,y2(this),x2(this),z2(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Em=function(a,b,c,d,e,f){return this.C?!1:t2.prototype.Em.call(this,a,b,c,d,e,f)};
g.h.Ep=function(a,b){b.stopPropagation();x2(this);z2(this,a);this.u.focus()};
g.h.dD=function(a){this.J=!0;this.Ep(500,a)};
g.h.cD=function(){this.J=!1;w2(this)};
g.h.VC=function(a){a.stopPropagation();this.hide()};
g.h.WC=function(a){a.stopPropagation();y2(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();t2.prototype.destroy.call(this)};g.r(A2,g.aQ);g.h=A2.prototype;g.h.wc=function(a,b){if(!C2(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.i_(b);c&&G2(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(q2(this.o,b),n1(this.player)),!0}return null};
g.h.getOptions=function(){return C2(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.un=function(){if(this.A){var a=g.wK(this.player).getVideoContentRect(!0);g.sg(this.A.element,a.width,a.height);g.ig(this.A.element,a.left,a.top)}if(this.o){var b=g.FK(this.player);a=this.o;b=b.width;g.L(a.D,"iv-drawer-small",426>=b);g.L(a.D,"iv-drawer-big",1280<=b)}};
g.h.TJ=function(a){this.dc(a.state);g.T(a.state,2)&&(this.Yj()&&this.yw()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.rq(!1))};
g.h.load=function(){g.aQ.prototype.load.call(this);this.dc(g.vK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.HI,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Wo()&&(c=H2(this,c));c={format:"XML",Vc:c,onError:d,od:{}};a.isPharma&&(c.od.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().G.get(b))&&I2(c,b);b=b&&(b.Fl||b.El);if(!a.tl||b)a.Cd?D2(this,a.Cd,c):(this.w=(0,g.x)(this.tE,this,c),this.player.addEventListener("videodatachange",this.w));g.OK(this.player,this.A.element,4);this.un();(b=a.Ja&&a.Ja.cards&&a.Ja.cards.cardCollectionRenderer||null)&&upa(this,b);(b=Hoa(a))&&b.featuredChannel&&vpa(this,b.featuredChannel,b.annotationId||"branding",
a.videoId||null,a.eventId||null)};
g.h.dc=function(a){a=!a.isCued()&&!g.T(a,1024);g.Gu(this.u,a);g.Gu(this.A,a)};
g.h.tE=function(a){var b=this.player.getVideoData();b.Cd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),D2(this,b.Cd,a))};
g.h.unload=function(){g.gR(this.player.app,"annotations_module",void 0);g.Ib(this.D,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,n1(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.D={};this.u.hide();g.aQ.prototype.unload.call(this);g.Fu(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.HI=function(a,b,c){this.C=null;!F2(this,b,a)&&(a=g.tp(c)&&c.responseXML?c.responseXML:null)&&(G2(this,a),g.K(this.player.getRootNode(),"iv-module-loaded"))};
g.h.Fy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?rpa(this):this.load())};
g.h.Yj=function(){return!!this.o&&this.o.isAvailable()};
g.h.yw=function(){this.Yj();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Yj();this.o&&(a?c?k2(this.o,c,b):k2(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):l2(this.o))};
g.h.rq=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.O().G.unsubscribe("vast_info_card_add",this.Fy,this);g.kn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.K,b=0,c=a.length;b<c;b++)g.Xo(a[b]);this.K.length=0;g.aQ.prototype.Y.call(this)};g.pQ.annotations_module=A2;g.pQ.creatorendscreen=D1;})(_yt_player);
