(function(g){var window=this;var m5=function(a){g.W.call(this,{F:"button",X:["ytp-offline-slate-button","ytp-button"],L:[{F:"div",I:"ytp-offline-slate-button-icon",W:"{{icon}}"},{F:"div",I:"ytp-offline-slate-button-text",W:"{{text}}"}]});this.C=a;this.A=this.w=null;this.hide();this.ga("click",this.D,this)},o5=function(a,b){!a.w&&b&&b.toggleButtonRenderer?a.w=b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.w=null);
n5(a)},n5=function(a){if(a.w){if(a.w.isToggled){var b=a.w.toggledText?g.PB(a.w.toggledText):"";
a.update({text:b,icon:p5(a.w.toggledIcon)})}else b=a.w.defaultText?g.PB(a.w.defaultText):"",a.update({text:b,icon:p5(a.w.defaultIcon)});a.show()}else a.hide()},p5=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS_NONE":return g.Y?{F:"div",X:["ytp-icon","ytp-icon-notifications-none"]}:{F:"svg",N:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},L:[{F:"path",N:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};case "NOTIFICATIONS_ACTIVE":return g.HM();default:return null}},q5=function(a){g.W.call(this,
{F:"div",
I:"ytp-offline-slate",L:[{F:"div",I:"ytp-offline-slate-bar",L:[{F:"span",I:"ytp-offline-slate-icon",L:[g.Y?{F:"div",X:["ytp-icon","ytp-icon-live-icon"]}:{F:"svg",N:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},L:[{F:"path",N:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{F:"circle",N:{cx:"12",cy:"12",r:"3"}}]}]},{F:"span",I:"ytp-offline-slate-buttons"},{F:"span",I:"ytp-offline-slate-messages",L:[{F:"div",I:"ytp-offline-slate-main-text",W:"{{maintext}}"},{F:"div",I:"ytp-offline-slate-subtitle-text",W:"{{subtitletext}}"}]}]}]});this.A=a;this.B=this.w=null;this.G=!1;this.C=new g.J(this.H,1E3,this);this.M(a,"presentingplayerstatechange",this.J);this.M(a,"livestatedata",this.D);this.hide();a=this.A.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&
this.D(a)},r5=function(a,b,c){if(b){var d=void 0!=b.subtitleText?g.PB(b.subtitleText):"";
b=c?c:void 0!=b.mainText?g.PB(b.mainText):"";a.update({maintext:b,subtitletext:d});g.L(a.element,"ytp-offline-slate-single-text-line",!d)}},v5=function(a){g.aQ.call(this,a);
this.G=!1;this.H=0;this.D=!1;this.o=NaN;this.u=this.w=null;this.B=!1;this.J=new g.tn(1E3,6E4,1);this.K=0;this.A=null;this.U=-(new g.nf).getTimezoneOffset();this.C=new g.Q(this);g.H(this,this.C);var b=this.player.getVideoData(),c=this.player.O();if(!b.ra)!g.R(c.experiments,"html5_release_post_live_heartbeat_killswitch")&&g.Xa(b.Ac,"heartbeat")&&g.LK(this.player,"heartbeat");else if(!g.Ox(c.w))g.HI(this.player.app.w,"html5.unsupportedlive","HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1",void 0);else if(g.R(c.experiments,
"live_fresca_v2")){this.G=this.B=!0;if(!g.ez(c)||g.tz(c))this.A=new q5(this.player),g.H(this,this.A),g.OK(this.player,this.A.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(this.u=b.playabilityStatus);this.u?(b=s5(this.u.liveStreamability&&this.u.liveStreamability.liveStreamabilityRenderer))?t5(this,b):t5(this,7500):t5(this,1E3)}this.C.M(a,"heartbeatparams",this.DE);this.C.M(a,"presentingplayerstatechange",this.EE);this.C.M(a,"videoplayerreset",this.oL);this.C.M(a,g.HD("heartbeat"),this.CE);
this.B&&this.u&&u5(this,this.u);b=new g.ED(1E3,0x7ffffffffffff,{priority:0,namespace:"heartbeat"});g.KK(a,[b])},w5=function(a){var b=a.player.getVideoData();
return!!g.pC(a.player.getVideoData())&&!b.Kv},x5=function(a){var b=a.player.getVideoData();
return w5(a)?!!a.w:!!b.heartbeatToken},t5=function(a,b){if(!a.o&&a.G){var c=a.player.getVideoData();
if(x5(a)||c.ra)void 0==b&&(b=a.D?a.B?7500:a.w?1E3*a.w.interval:a.player.getVideoData().Ev||6E4:1E3),a.o=g.xo((0,g.x)(a.gM,a),b)}},u5=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!c.switchStreamsImmediately),e=s5(c),f=a.player.getVideoData();
if(g.Nt(g.vK(a.player))&&!g.CC(f)&&!a.player.isAtLiveHead()&&!d)return e;var k=(d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint)&&d.videoId;if(k)return g.MT(a.player.app,k,void 0,void 0,!0,d),e;if("OK"==b.status.toUpperCase()){d=c&&c.broadcastId;k=a.u&&a.u.liveStreamability&&a.u.liveStreamability.liveStreamabilityRenderer&&a.u.liveStreamability.liveStreamabilityRenderer.broadcastId;if(!f.hlsvp&&!f.Ed||d!=k)return c={video_id:f.videoId},f.wm&&(c.is_live_destination="1"),c.autonav_state=
f.autonavState,a.player.loadVideoByPlayerVars(c),e;g.LK(a.player,"heartbeat")}c&&c.displayEndscreen&&a.A&&(f=a.A,f.G=!0,f.Ha()&&g.qT(f.A.app,void 0));return e},s5=function(a){var b=0;
a&&a.pollDelayMs&&(a=parseInt(a.pollDelayMs,10))&&(b=a);return b},y5=function(a,b,c){if(a.o){a.o=NaN;
a.H++;var d=a.player.getVideoData();(d.Gv||b&&!g.pC(a.player.getVideoData())&&!x5(a)&&d.ra?0:a.H>=(a.w?a.w.o:d.Fv||5))?(b=b?"heartbeat.net":"heartbeat.servererror",(d=a.player.getVideoData())&&d.ra?g.HI(a.player.app.w,b,"Video playback interrupted. Please try again.",c,void 0):g.HI(a.player.app.w,b,"Sorry, there was an error licensing this video.",c,void 0)):(t5(a,a.J.getValue()),g.un(a.J))}},z5=function(a){a.H=0;
a.o&&(g.zo(a.o),a.o=NaN);a.D=!1;a.K=0},A5=function(a){try{var b=JSON.parse(a);
return null!=b?b:null}catch(c){return null}};
g.r(m5,g.W);
m5.prototype.D=function(){this.A||(this.A=new g.ur(this.C.O().ya));var a=g.Jq(this.A.o);g.$A()&&(a.context.clientScreenNonce=g.$A());var b;if(this.w.isToggled){if(b=(b=this.w.toggledServiceEndpoint)&&b.removeUpcomingEventReminderEndpoint&&b.removeUpcomingEventReminderEndpoint.params)a.params=b;b="notification/remove_upcoming_event_reminder"}else{if(b=(b=this.w.defaultServiceEndpoint)&&b.addUpcomingEventReminderEndpoint&&b.addUpcomingEventReminderEndpoint.params)a.params=b;b="notification/add_upcoming_event_reminder"}var c={timeout:5E3};
c.onError=(0,g.x)(this.B,this);c.Md=(0,g.x)(this.B,this);g.Nq(this.A,b,a,c);this.w.isToggled=!this.w.isToggled;n5(this)};
m5.prototype.B=function(){this.w&&(this.w.isToggled=!this.w.isToggled,n5(this))};g.r(q5,g.W);
q5.prototype.D=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.w=a;b=b.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.H():r5(this,b);var c=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail;if(c){for(var d=
0,e=null,f=0;f<c.thumbnails.length;f++)c.thumbnails[f].width>d&&(d=c.thumbnails[f].width,e=c.thumbnails[f].url);e&&(this.element.style.backgroundImage="url("+e+")")}else this.element.style.backgroundImage="";b.actionButtons?(this.B||(this.B=new m5(this.A),this.B.o(this.u["ytp-offline-slate-buttons"]),g.H(this,this.B)),o5(this.B,b.actionButtons[0])):this.B&&o5(this.B,null);this.w=a}else this.w=null;this.J()};
q5.prototype.J=function(){var a=g.vK(this.A),b=this.A.getVideoData(),c=b.ra&&(g.Qt(a)||g.T(a,2)||g.T(a,64)),d=2==b.autonavState&&g.T(a,2);a=g.Nt(a)&&!g.CC(b)&&!this.A.isAtLiveHead(!0);c&&!a&&!d&&this.w&&"LIVE_STREAM_OFFLINE"==this.w.status.toUpperCase()?this.Ha()||(this.show(),this.A.R("offlineslatestatechange"),this.G&&g.qT(this.A.app,void 0)):this.Ha()&&(this.hide(),this.A.R("offlineslatestatechange"))};
q5.prototype.H=function(){var a=this.w&&this.w.liveStreamability&&this.w.liveStreamability.liveStreamabilityRenderer&&this.w.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.w.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor((0,g.A)()/1E3),c=a.canShowCountdown&&parseInt(a.scheduledStartTime,10);!c||c<=b?(r5(this,a),this.C.stop()):(b=g.lM(c-b),r5(this,a,b),g.Zm(this.C))}};
q5.prototype.Y=function(){this.C.dispose();this.C=null;g.W.prototype.Y.call(this)};g.r(v5,g.aQ);g.h=v5.prototype;g.h.Y=function(){z5(this);g.gR(this.player.app,"heartbeat",void 0);g.aQ.prototype.Y.call(this)};
g.h.CE=function(){this.G=!0;t5(this,2E3)};
g.h.DE=function(a){this.w=a;t5(this,2E3)};
g.h.EE=function(a){g.T(a.state,2)||g.T(a.state,64)?(z5(this),this.B&&(this.G=!0,t5(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&t5(this,2E3)};
g.h.oL=function(){3!==this.player.getPresentingPlayerType()&&t5(this,2E3)};
g.h.gM=function(){var a=this.player.O(),b=this.player.getVideoData();var c=a.B;if(3==this.player.getPresentingPlayerType())this.o=NaN;else if(g.T(g.vK(this.player),4))this.o=NaN;else if(x5(this)||b.ra){if(!w5(this)||b.ra){var d="GET";var e=a.deviceParams;a={video_id:b.videoId,heartbeat_token:b.heartbeatToken,c:e.c,cver:e.cver,cbrand:e.cbrand,cmodel:e.cmodel,vvt:b.Ze,mdx_environment:b.mdxEnvironment,access_token:b.oauthToken,forced_experiments:a.wa,utc_offset_minutes:this.U,upg_content_filter_mode:b.ao,
sequence_number:this.K};e=this.player.O();void 0!=e.homeGroupInfo?a.home_group_info=e.homeGroupInfo:void 0!=b.homeGroupInfo&&(a.home_group_info=b.homeGroupInfo);void 0!=e.livingRoomAppMode&&(a.living_room_app_mode=e.livingRoomAppMode);(e="undefined"!=typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)&&(a.time_zone=e);(e=g.lC(b))&&(a.uloc=e);(e=this.player.getProgressState().ingestionTime)&&isFinite(e)&&(a.ingestion_time=e);c=g.Ff(c+"heartbeat",a)}else d="GET",c=g.Ff(this.w.url,
{request_id:g.bu()}),b.Ze&&(c=g.Ff(c,{vvt:b.Ze}),b.mdxEnvironment&&(c=g.Ff(c,{mdx_environment:b.mdxEnvironment}))),b.oauthToken&&(c=g.Ff(c,{access_token:b.oauthToken}));b.Kj&&(c=g.Ff(c,{internalipoverride:b.Kj}));a={cpn:b.clientPlaybackNonce};b.contextParams&&(a.context_params=b.contextParams);c=g.Ff(c,a);g.zp(c,{format:"RAW",method:d,timeout:3E4,onSuccess:(0,g.x)(this.SD,this),onError:(0,g.x)(this.RD,this),Md:(0,g.x)(this.TD,this),withCredentials:!0})}else z5(this)};
g.h.SD=function(a){if(this.o){this.J.reset();this.K++;a=a.responseText;var b=A5(a);if(b){this.player.ka("onHeartbeat",b);var c="ok"==b.status?b.stop_heartbeat?2:0:"stop"==b.status?1:"live_stream_offline"==b.status?0:-1}else c=(c=a.match(B5))?"0"==c[1]?0:1:-1;if(-1==c)b="decode",window.btoa&&(b+=" "+window.btoa(a)),y5(this,!1,b);else if(2!=c||x5(this))if(this.H=0,this.o=NaN,1==c){this.D=!1;b=this.player;c="LICENSE";var d=A5(a);d?a=d.reason||g.gJ[c]||"":((a=a.match(B5))&&(a=parseInt(a[1],10))&&(c=g.Ct(a)),
a=g.gJ[c]||"");g.HI(b.app.w,"heartbeat.stop",a,void 0,void 0)}else this.D=!0,a=0,this.B&&b&&(a=u5(this,b),this.player.R("livestatedata",b)),a?t5(this,a):t5(this);else z5(this),this.D=!0}};
g.h.RD=function(a){y5(this,!0,"net-"+a.status)};
g.h.TD=function(){y5(this,!0,"timeout")};
g.h.BE=function(){return!!this.A&&this.A.Ha()};
var B5=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.pQ.heartbeat=v5;})(_yt_player);
